export const zodErrorsString = "Zod Errors";
export const similarUserExistsString = "User with similar username or email exists";
export const issueWithDatabaseString = "Issue talking to the database";
export const createdNewUserString = "Successfully created a new user";
export const noRequestBodyString = "No request body given";
export const userNotFoundString = "User not found";
export const invalidPassword = "Incorrect password";
export const loginSuccess = "Login successful";
export const relogin = "Login before using the service"
